### PR TITLE
EVG-18898 upgrade mongo db version

### PR DESCRIPTION
**Pull request by ybrill**
[EVG-18898](https://jira.mongodb.org/browse/EVG-18898)

### Description 
Same idea as https://github.com/evergreen-ci/spruce/pull/1844. This will upgrade the db to be in sync with evergreen's post https://github.com/evergreen-ci/evergreen/pull/6542. Also upgrade to ubuntu22.04. We're all clear to upgrade the go version as well but that's not here since it's configured by a project variable.

### Screenshots
N/A

### Testing 
Made [a patch](https://spruce.mongodb.com/version/646e64a30305b9ddaa5b762a/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC) to test with the evergreen changes as a module (since this PRs test's won't have them).

### Evergreen PR 
https://github.com/evergreen-ci/evergreen/pull/6542

### CODE REVIEW

**Comment by ybrill** [comment]
@khelif96 I just saw on my patch that [check-codegen](https://spruce.mongodb.com/task/parsley_ubuntu2204_small_check_codegen_patch_24f060a22a5ef6188d0438b3641a0727b433d4a4_646e64a30305b9ddaa5b762a_23_05_24_19_31_54/logs?execution=0) is failing. 
Does that seem like it could be related?

**Comment by khelif96** [comment]
> @khelif96 I just saw on my patch that [check-codegen](https://spruce.mongodb.com/task/parsley_ubuntu2204_small_check_codegen_patch_24f060a22a5ef6188d0438b3641a0727b433d4a4_646e64a30305b9ddaa5b762a_23_05_24_19_31_54/logs?execution=0) is failing. Does that seem like it could be related?

Nope, it just means there was a schema change on evergreen that wasn't made here yet, you can ignore it.

**Comment by ybrill** [comment]
Perfect. Thank you!

**Comment by ybrill** [comment]
evergreen retry

**Pull request merged**
